### ISSUE TITLE
"@electron/remote is disabled for this WebContents" with mutiple BrowserWindows

### ISSUE THREAD

**Issue by Elyspio** [electron/remote#112]
Hello, 

I have some an issue with the @electron/remote "enable" method.

It works fine for the first BrowserWindow (created by the main process).

But it gives me the following error when I'm doing it from the created window : "@electron/remote is disabled for this WebContents. Call require("@electron/remote/main").enable(webContents) to enable it".

Here is my code:

```ts

const { dialog, BrowserWindow, require: nodeRequire } = require("@electron/remote");


// called from the renderer process

const win = new BrowserWindow({
    ...windowOption,
});

nodeRequire("@electron/remote/main").enable(win.webContents);

win.loadURL(...)


```

I'm using electron 17 and @electron/remote 2.0.5

Do you have any tips please ?

Sincerely

**Comment by ncaq** [comment]
I tried this comment and it probably solves the problem.
https://github.com/electron/remote/issues/94#issuecomment-1024849702
