### ISSUE TITLE
Electron >=v13.0.0-beta.6 required to support sandboxed renderers

### ISSUE THREAD

**Issue by snaildos** [electron/remote#130]
![image](https://user-images.githubusercontent.com/46210117/168550209-c4c97eb4-3ef9-4325-9fb1-bc538bfb1475.png)
![image](https://user-images.githubusercontent.com/46210117/168550249-65512774-aea1-4024-bd8d-c816f6d9d7d0.png)

**Comment by snaildos** [comment]
Versions installed:
"@electron/remote": "2.0.1",
"electron": "^17.0.0",

What I tried:
I tried to remote: "2.0.8" and the issue still persists.

**Comment by toghrulgasimov** [comment]
I have this problem too

**Comment by snaildos** [comment]
> I have this problem too

Yeah, clearly it's a remote bug.

**Comment by snaildos** [comment]
Regarding reproduction,
I do not have the time to create a reproduction repo, 
you could check my Fifo Browser repo, and run a development environment in there. 
Or maybe someone else can send a repo that isn't a whole entire browser with assets that make it hard to debug. 👍 
Thanks all!

**Comment by piotrmod92** [comment]
Hi,

I encountered the same problem when using @electron/remote v2.0.8 and any electron >= v14.0.0.
It seems the function getContextId() in remote.js cannot find v8_util binding - getElectronBinding('v8_util') returns null:

![image](https://user-images.githubusercontent.com/9364152/170262192-d2d73f1e-43ee-4116-a127-a5293b60cb6d.png)

Any ideas how to work it around?

Thanks in advance!

**Comment by snaildos** [comment]
> Hi,
> 
> I encountered the same problem when using @electron/remote v2.0.8 and any electron >= v14.0.0. It seems the function getContextId() in remote.js cannot find v8_util binding - getElectronBinding('v8_util') returns null:
> 
> ![image](https://user-images.githubusercontent.com/9364152/170262192-d2d73f1e-43ee-4116-a127-a5293b60cb6d.png)
> 
> Any ideas how to work it around?
> 
> Thanks in advance!

Hi! Thanks for adding to the issue. Please @erickzhao refer to this issue and see if they can fix this.

**Comment by freestlr** [comment]
Hi! I beleive the source of the issue is **webpack 5** and it's node polyfill removed.

from [https://webpack.js.org/migrate/5/](https://webpack.js.org/migrate/5/):
> webpack 5 does no longer include a polyfill for this Node.js variable. Avoid using it in the frontend code.

.
`remote` is using `process._linkedBinding` underneath which is undefined in webpack 5 builds.
The obvious solution to include fallback to webpack config doesn't work:
```javascript
resolve.fallback.process = require.resolve('process'); // does no effect
```
as well as installing [node-polyfill-webpack-plugin](https://github.com/Richienb/node-polyfill-webpack-plugin).

Cheers!

**Comment by MatanYemini** [comment]
Hi!

I am also getting the above issue ^ any ideas? 

I don't mind jumping on it if you have a direction.

:)

**Comment by snaildos** [comment]
Hi everyone trying to contribute, thanks @freestlr , I managed to work it out looking at the previous issue, you can see this commit
https://github.com/QiYuTechDev/ElectronRemote/commit/b57f77157821bba7777f151514194a61ed8316ea
was used to fix it, and it worked.
Thank you all for your time!
Kind regards,
Snail

**Comment by uffou** [comment]
I have this same error with webpack 4 and electron 20

No clue how to fix that. Going to give it another hour and then will start to remove remote from the app.
