### ISSUE TITLE
fix 180 isn't in 2.1.2, so fails for electron 30.

### ISSUE THREAD

**Issue by Kilian** [electron/remote#184]
The fix for 2.1.2 isn't in the version that's currently on NPM. `dist/src/modules-names.js currently has the following JS:

```
if (((_b = features === null || features === void 0 ? void 0 : features.isViewApiEnabled) === null || _b === void 0 ? void 0 : _b.call(features)) !== false) {
    exports.browserModuleNames.push('ImageView');
}
```
Which now breaks on features.isViewApiEnabled again like #179

**Comment by Kilian** [comment]
Whelp nevermind, it was a subdepencency.

**Comment by Nantris** [comment]
@Kilian do you know what sub-dependency you faced this issue with? It sure seems like @electron/remote to me, but I'm guessing I'm overlooking something in the stack trace given that you got it working.
