### ISSUE TITLE
print with deviceName does not work after migrating to electron v12

### ISSUE THREAD

**Issue by mrafei** [electron/remote#29]
Hello, I have migrated my application to 12.0.0-beta.11 and I am using @electron/remote v^1.0.2.

I noticed that the following code is not working properly:
```javascript
      const { getCurrentWebContents } = require('@electron/remote')
      getCurrentWebContents().print(
          {
            silent: true,
            deviceName: "exampleDevice",
            copies: 1,
            landscape: false,
            margins: { marginType: "none" },
          },
```
This only prints to selected default printer in windows. 
appreciate the help.

**Comment by miniak** [comment]
This issue has nothing to do with remote. It might be this Electron issue https://github.com/electron/electron/issues/30340
