### ISSUE TITLE
typescript declaration

### ISSUE THREAD

**Issue by taoqf** [electron/remote#35]
v1.0.2 still does not contains declaration.
https://github.com/electron/remote/pull/25

**Comment by nornagon** [comment]
@taoqf that PR was released in 1.0.3, so that's the earliest version that will contain the published TS defs.

**Comment by taoqf** [comment]
... I could not see 1.0.3 https://www.npmjs.com/package/@electron/remote, or this is published in other name?

**Comment by nornagon** [comment]
ah, looks like they haven't been published 🤔  i'll look into it.

**Comment by nornagon** [comment]
1.0.4 is now published.

**Comment by taoqf** [comment]
...
But the types could not be used, cause they are not in correct path.

**Comment by nornagon** [comment]
@taoqf would you mind opening a new issue and tagging @ffflorian, who wrote the PR?

**Comment by taoqf** [comment]
I gaved up and changed to ipc.

**Comment by ffflorian** [comment]
@taoqf 
> But the types could not be used, cause they are not in correct path.

What's the problem with the types? What do you mean by "they are not in the correct path"?

**Comment by ffflorian** [comment]
I noticed there is indeed an untyped file which might lead to confusion. I created a PR.
