### ISSUE TITLE
Guide to replace remote module with better writing style

### ISSUE THREAD

**Issue by linonetwo** [electron/remote#37]
Can there be a guide to teach us how to replace things like `remote.getCurrentWindow()` to something better?

I can't find a good article for this, only an article telling remote module should be replaced by something better (https://medium.com/@nornagon/electrons-remote-module-considered-harmful-70d69500f31) which is somehow useless.

**Comment by nornagon** [comment]
There's some guidance in that article you linked about ["What to do instead"](https://medium.com/@nornagon/electrons-remote-module-considered-harmful-70d69500f31#d978), though it doesn't specifically discuss `remote.getCurrentWindow()`. In general, the way to replace `remote` usage is by sending IPC messages to the main process, through `ipcRenderer.invoke()` or `ipcRenderer.send()`, and performing the logic in the main process instead.

Presumably you are doing something more than just _getting_ the current window—are you reading some property of it? Showing a menu? Something else? With more detail about what you're trying to accomplish, I might be better able to direct you.

I'm closing this as we use the issue tracker is used for feature requests and bug reports, but I'm happy to continue discussion here. You may also have some luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

Hope this helps!

**Comment by lutzroeder** [comment]
@nornagon this is an often used scenario for showing a dialog attached to the current window.

How can this be accomplished via `ipcRenderer.invokeSync()`?

```javascript
const owner = electron.remote.getCurrentWindow();
electron.remote.dialog.showMessageBoxSync(owner, { type: 'error', message: message, detail: detail });
```

**Comment by lutzroeder** [comment]
Answer:

```javascript
electron.ipcMain.on('show-message-box', (event, options) => {
    const owner = event.sender.getOwnerBrowserWindow();
    electron.dialog.showMessageBoxSync(owner, options);
});
```

**Comment by linonetwo** [comment]
@lutzroeder I think sendSync will slowdown the renderer, so I always use ipc.invoke(). And there seem to be no `event.sender` in ipc.invoke()

I'm now using an window manager class, to hold all created browser window, and have a `get()` method to get window by name. So in renderer process, I can pass the name to main process, and main process get window by name, this is my version of `remote.getCurrentWindow()`.  https://github.com/tiddly-gittly/TiddlyGit-Desktop/blob/c727ac2f910e6f05cf2fd5f1ef8f86e48355e333/src/services/windows/index.ts#L90

And I'm not using ipc directly, I wrap them into proxy: https://github.com/tiddly-gittly/TiddlyGit-Desktop/blob/c727ac2f910e6f05cf2fd5f1ef8f86e48355e333/src/preload/common/services.ts#L43

Using electron-ipc-proxy https://github.com/tiddly-gittly/TiddlyGit-Desktop/tree/refactor/typescript/src/helpers/electron-ipc-proxy

**Comment by nornagon** [comment]
> And there seem to be no `event.sender` in ipc.invoke()

`ipcMain.handle()` does provide the sender. https://www.electronjs.org/docs/api/structures/ipc-main-invoke-event

e.g.

```
ipcMain.handle('my-event', (event) => {
  event.sender // this works :)
})
```

**Comment by linonetwo** [comment]
Sadly, there is something very difficult to accomplish: build context-menu

we can use `window.document.addEventListener('contextmenu', openContextMenuForWindow);` instead of `webContents.on('context-menu', openContextMenuForWindow);`, but
to do things on current window, we have to `this.webContents.showDefinitionForSelection()` or `webContents.canGoBack()`, but we don't have access to `webContents` in renderer.

To do things in the renderer process, we have to send menu config item with callback to the main process, but sending object with callback is very hard to achieve.

**Comment by linonetwo** [comment]
Is there a safe package to "Passing callbacks to the main process"?

I think I can iterate through the object, replace each object method with a random uuid, and send this object without a callback to the main thread.

And I register `IPCRenderer.on(uuid` for each object method, and reconstruct the object with callback on the main process, the callback is just `IPCMain.invoke(uuid`. Is there any existing package to do so?
