### ISSUE TITLE
The main process and the renderer process share logic

### ISSUE THREAD

**Issue by GuoSirius** [electron/remote#41]
The module for `@electron/remote` will throw an exception that will cause the code to not run. You can optimize it by simply warning the user

```TS
import electron from 'electron'
import * as remote from '@electron/remote'

const app = electron.app || remote.app
const ipcMain = electron.ipcMain || remote.ipcMain
const BrowserWindow = electron.BrowserWindow || remote.BrowserWindow

// Here's the common code
```

**Comment by nornagon** [comment]
Am I right in understanding that you're trying to write code that will work in either the main or the renderer process?

Importing `@electron/remote` in the main process throws an error:

```
Error: "@electron/remote" cannot be required in the browser process. Instead require("@electron/remote/main").
```

You can work around this by checking which process you're in and importing conditionally, e.g. with `require()`.

I'm closing this for now as I don't believe there's anything further to be done, but let me know if I've misunderstood.
