### ISSUE TITLE
TypeError: process._linkedBinding is not a function  in renderer at electron@12.0.0

### ISSUE THREAD

**Issue by nomagick** [electron/remote#42]
TypeError: process._linkedBinding is not a function  

in renderer preload script 

while running  require('@electron/remote');

at electron@12.0.0

using browserify as preload bundler.

**Comment by nornagon** [comment]
Related: https://github.com/electron/remote/pull/38

I think this is because `process._linkedBinding` isn't available in sandboxed renderers. Is there any chance you're using `sandbox: true`?

**Comment by nomagick** [comment]
@nornagon  True.  I did enabled the sandbox feature.  

The original remote module was able to be used in sandboxed renderers .

Is it that `@electron/remote` would not work in sandboxed renderers ?

Then I think it's better to mention this explicitly in readme.

I use remote for debug reasons. 
It's very handy to check on the main process from a renderer devtools even on a distributed sandboxed app.

**Comment by nornagon** [comment]
Should be fixed by #44.

**Comment by nornagon** [comment]
FWIW, I don't recommend using `remote` from a sandboxed process as it largely defeats the purpose of sandboxing.

**Comment by nomagick** [comment]
Thanks.

`remote` would only be loaded dynamiclly by a custom function defined in `preload` script and only for debugging. 

I think the convenience worth it.
