### ISSUE TITLE
Electron >=v13.0.0-beta.6 required to support sandboxed renderers

### ISSUE THREAD

**Issue by QiYuTechDev** [electron/remote#61]
BrowserWindow `webPreferences` setting is:
```json
{
    "nodeIntegration": true,
    "contextIsolation": false,
    "sandbox": false,
    "enableRemoteModule": true,
}
```

## Demo code:

```ts
import {dialog} from "@electron/remote";
```

It seems the demo code works on electron 12.x but broken with 13.0.1 version.

**Comment by nornagon** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by nornagon** [comment]
The module seems to be working OK on 13.0.1, as shown by this [Fiddle](/electron/fiddle): https://gist.github.com/0088222a5bd8e87d6e73fa006e4c18ff

What problem are you having?

**Comment by QiYuTechDev** [comment]
I build a demo app to reproduce the bug:

source code: https://github.com/QiYuTechDev/ElectronRemote

**Comment by QiYuTechDev** [comment]
It seem https://github.com/QiYuTechDev/ElectronRemote/commit/b57f77157821bba7777f151514194a61ed8316ea can fix this problem

**Comment by spcBackToLife** [comment]
> It seem [QiYuTechDev/ElectronRemote@b57f771](https://github.com/QiYuTechDev/ElectronRemote/commit/b57f77157821bba7777f151514194a61ed8316ea) can fix this problem

I tried, it seems still has this problem = =.

**Comment by amoscatelli** [comment]
It still has this problem ...

**Comment by geroale** [comment]
Same issue here

**Comment by snaildos** [comment]
#130

**Comment by illiterate-txp** [comment]
I solve the problem with `const {dialog} = require('electron').remote`

**Comment by OldManMeta** [comment]
this is still happening

**Comment by erickzhao** [comment]
https://github.com/electron/remote/issues/130#issuecomment-1150535397

This might help.
